import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import { ethers } from "ethers";
import { useState, useEffect } from "react";
import { abi } from "../../constants/abi";

const inter = Inter({ subsets: ['latin'] })

const endpoint = process.env.NEXT_PUBLIC_ENDPOINT;
const provider = new ethers.providers.JsonRpcProvider(endpoint);
const contractAddress = "0x690C775dD85365a0b288B30c338ca1E725abD50E";
const gov = new ethers.Contract(contractAddress, abi, provider);

export default function Home() {
  const [block, setBlock] = useState(0);
  const [manifesto, setManifesto] = useState("");
  // const [allProposals, setProposals] = useState()

  const getBlock = async () => {
    const blockNumber = await provider.getBlockNumber();
    console.log("block:", blockNumber);
    setBlock(blockNumber);
  }

  const getManifesto = async () => {
    const getManifesto = await gov.manifesto();
    setManifesto(getManifesto);
  }

  const getProposals = async () => {
    if (block > 1) {
      const proposals = await gov.queryFilter("ProposalCreated", 8251080, block);
      try {
        let i:number = 0
        if (proposals[0].args != undefined) {
          for( i; i < Number(proposals.length) ; i++) {
            console.log("Proposal #"+ i + ":", String(proposals[i].args?.proposalId) );
          }
        }
      } catch(error) {
        console.log("error:", error)
      }
    }
    
  }

  useEffect(() => {
    getBlock();
    getManifesto();
    getProposals();
  });

  return (
    <>
      <Head>
        <title>Gov UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.description}>
          <p>
          <a
              href="https://github.com/w3hc/gov"
              target="_blank"
              rel="noopener noreferrer"
            >Gov
          </a>
          </p>
          <div>
            <a
              href="https://github.com/w3hc"
              target="_blank"
              rel="noopener noreferrer"
            >
            </a>
          </div>
        </div>
        
        <div className={inter.className}>
  
          <p>Current block number: <strong>{block}</strong></p><br />
          <p>Gov contract address: <strong><a target="_blank" rel="noopener noreferrer" href="https://goerli.etherscan.io/address/0x690C775dD85365a0b288B30c338ca1E725abD50E#code">{contractAddress}</a></strong></p><br />
          <p>Manifesto: <a target="_blank" rel="noopener noreferrer" href="https://bafybeihmgfg2gmm23ozur3ylmkxgwkyr5dlpruivv3wjeujrdktxihqe3a.ipfs.w3s.link/manifesto.md"><strong>{manifesto}</strong></a></p><br />
          {/* <p>Latest proposal: <a target="_blank" rel="noopener noreferrer" href="https://www.tally.xyz/gov/girlygov-64/proposal/95129343070641600225540803920375046071595778808183352464012422526749827081032"><strong>95129...81032</strong></a></p> */}
          <h3>Proposals: </h3><br /><br />
          <a target="_blank" rel="noopener noreferrer" href="https://www.tally.xyz/gov/girlygov-64/proposal/95129343070641600225540803920375046071595778808183352464012422526749827081032"><strong>95129...81032</strong></a>

        </div>

        <div className={styles.grid}>
          <Link
            href="/"
            className={styles.card}
            
          >
            <h2 className={inter.className}>
              Home <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              What&apos;s happening on your homepage?
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
