import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Link from 'next/link'
import { ethers } from "ethers";
import { useState, useEffect } from "react";
import { abi } from "../../constants/abi";

const inter = Inter({ subsets: ['latin'] })

const endpoint = process.env.NEXT_PUBLIC_ENDPOINT;
const provider = new ethers.providers.JsonRpcProvider(endpoint);
// const signer = provider.getSigner()
const contractAddress = "0x690C775dD85365a0b288B30c338ca1E725abD50E";

export default function Home() {
  const [block, setBlock] = useState(0);
  const [manifesto, setManifesto] = useState("");

  const getBlock = async () => {
    const blockNumber = await provider.getBlockNumber();
    console.log("block:", blockNumber);
    setBlock(blockNumber);
  }

  const getManifesto = async () => {
    // console.log("abi:", abi);
    const gov = new ethers.Contract(contractAddress, abi, provider);
    const getManifesto = await gov.manifesto();
    setManifesto(getManifesto);
  }

  useEffect(() => {
    getBlock();
    getManifesto();
  },[]);

  return (
    <>
      <Head>
        <title>Gov UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className={styles.description}>
          <p>
          <a
              href="https://github.com/w3hc/gov"
              target="_blank"
              rel="noopener noreferrer"
            >Gov
          </a>
          </p>
          <div>
            <a
              href="https://github.com/w3hc"
              target="_blank"
              rel="noopener noreferrer"
            >
            </a>
          </div>
        </div>
        
        <div className={inter.className}>
  
          <p>Current block number: <strong>{block}</strong></p><br />
          <p>Gov contract address: <strong><a href="https://goerli.etherscan.io/address/0x690C775dD85365a0b288B30c338ca1E725abD50E#code">{contractAddress}</a></strong></p><br />
          <p>Manifesto: <a href="https://bafybeihmgfg2gmm23ozur3ylmkxgwkyr5dlpruivv3wjeujrdktxihqe3a.ipfs.w3s.link/"><strong>{manifesto}</strong></a></p>
          
        </div>

        <div className={styles.grid}>
          <Link
            href="/"
            className={styles.card}
            
          >
            <h2 className={inter.className}>
              Home <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              What&apos;s happening on your homepage?
            </p>
          </Link>
        </div>
      </main>
    </>
  )
}
