import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gov UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Gov
          </p>
          <div>
            <a
              href="https://github.com/w3hc"
              target="_blank"
              rel="noopener noreferrer"
            >
            </a>
          </div>
        </div>

        <div className={inter.className}>
          Hello world!
        </div>

        <div className={styles.grid}>
          <Link
            href="/activity"
            className={styles.card}
            
          >
            <h2 className={inter.className}>
              Activity <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              What&apos;s happening in your DAO?
            </p>
            </Link>
        </div>
      </main>
    </>
  )
}
